import type { Metadata } from "next";
import localFont from 'next/font/local'
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "../style/globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const petrovFont = localFont({
  src: './fonts/PetrovSans-Regular.ttf',
  variable: '--font-petrov',
})

export const metadata: Metadata = {
  title: "MCF1 Starter Kit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${petrovFont.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <Header />
        {children}
        <Footer/>
</ThemeProvider>
      </body>
    </html>
  );
}
